spring:
  datasource:
    username: app_user
    password: q1w2e3sedama
    url: jdbc:postgresql://localhost:5432/hdgh0g
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

security:
  admin:
    password:
      file: adminpass

server:
  port: 9000

storage:
  prefix: http://static.hdgh0g.com/
  directory: $/home/backend/storage
  filename:
    length: 32