CREATE TABLE images
(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  url VARCHAR(1024) NOT NULL,
  thumbnail_url VARCHAR(1024) NOT NULL
);

CREATE TABLE technologies
(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  caption VARCHAR(1024) NOT NULL,
  image_id BIGINT REFERENCES images (id) ON DELETE SET NULL
);

CREATE TABLE contacts
(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(1024) NOT NULL,
  description VARCHAR(1024) NOT NULL,
  url VARCHAR(1024),
  image_id BIGINT REFERENCES images (id) ON DELETE SET NULL
);

CREATE TABLE projects
(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(1024) NOT NULL,
  description TEXT NOT NULL,
  image_id BIGINT REFERENCES images (id) ON DELETE SET NULL
)